server {
    listen 8080;

    root ./www/sites/sites;

    location / {
        methods GET POST DELETE;
        index index.html;
        autoindex on; 
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }
}