# Primary Server: Handles the main site and uploads
server 
{
    listen 8080;
    host 0.0.0.0;
    server_name example.com www.example.com;
    
    # Root directory for this server
    root ./www;
    index index.html;
    
    # 1MB limit for uploads
    client_max_body_size 1GB; # handle other storage prefix

    # Custom Error Pages (Ensure these files exist in ./www)
    error_page 404 /404.html;
    error_page 500 502 503 /50x.html;

    # Default Location
    # location / {
    #     methods GET;
    #     autoindex on; # Allows directory listing
    # }

    location /old
    {
        return 301 /new;
    }

    location /temp {
        return 302 /new;
    }

    location /external {
        return 302 https://github.com/Mohamed-Talb/WEBSERV;
    }

    location /new {
        methods GET;
        root ./www;
        index index.html;
    }

    location /docs {
    methods GET;
    root ./www/docs;
    autoindex on;
    }

    # Uploads Location
    # Note: If your project treats 'root' as the path prepended to URI, 
    # ensure this points to the correct folder.
    location /upload {
        methods POST DELETE GET;
        root ./upload;      # This makes the full path ./upload/
        autoindex on;
        upload on;
        upload_path ./www/upload;
    }

    # CGI Location
    location /cgi{
        methods GET POST;
        root ./www/cgi_bin;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
    }
}

# Secondary Server: Handles test traffic
server 
{
    listen 9090;
    host 0.0.0.0;
    server_name test.com;
    root ./test_site;

    location / {
        methods GET POST;
        index test.html;
    }
}