server {
    listen 0.0.0.0:8080;
    server_name localhost;

    root .;
    client_max_body_size 1000000;

    location / {
        methods GET;
        root .;
        autoindex off;
    }

    location /post_body {
        methods POST;
        root .;
        client_max_body_size 100;
        autoindex off;
    }

    location /directory {
        methods GET;
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
    }

    location /directory/youpi.bla {
        methods POST;
        root ./YoupiBanane;
        cgi_ext .bla;
        cgi_path ./cgi_test;
        autoindex off;
    }

    location /directory/nop/other.pouic {
        methods GET;
        root ./YoupiBanane;
        autoindex off;
    }
}