server 
{
    listen 8080;
    server_name localhost;

    root ./www/Webserv42;
    index index.html;
    client_max_body_size 10000000;

    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;
    error_page 501 /errors/501.html;
    error_page 504 /errors/504.html;

    location / 
    {
        methods GET;
        root ./www/Webserv42;
        index index.html;
        autoindex off;
    }

    location /upload 
    {
        methods GET POST DELETE;
        root ./www/Webserv42/upload;
        upload on;
        upload_path upload;
        client_max_body_size 10000000;
        autoindex on;
    }

    location /cgi_bin 
    {
        methods GET POST;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php;
        cgi_pass .sh /bin/bash;
        root ./www/Webserv42/cgi_bin;
        client_max_body_size 10000000;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name alpha.local;

    root ./www/virtual/alpha;
    index index.html;

    location / {
        methods GET;
        root ./www/virtual/alpha;
        index index.html;
        autoindex off;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name beta.local;

    root ./www/virtual/beta;
    index index.html;

    location / {
        methods GET;
        root ./www/virtual/beta;
        index index.html;
        autoindex off;
    }
}

server {
    listen 127.0.0.1:9090;
    server_name localhost;

    root ./www/virtual/port9090;
    index index.html;

    location / {
        methods GET;
        root ./www/virtual/port9090;
        index index.html;
        autoindex off;
    }
}